"""governor_vectors.py - shared test vectors: the Python governor (oracle) decides, the C++ port must agree.

    python3 catalogue/tools/governor_vectors.py    # writes engine/social/tests/governor_vectors.inc

Deterministic (fixed seed). Writes are replayed as sequences on one ledger; gestures are random parameter
combinations with adult, minor, unknown and name-only parties.
"""
from __future__ import annotations

import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT)); sys.path.insert(0, str(ROOT / "tools"))
from schema import Catalogue  # noqa: E402
from governor import Governor, Party, WriteLedger, tenths  # noqa: E402
from gen_cpp import ident  # noqa: E402

OUT = ROOT.parent / "engine" / "social" / "tests" / "governor_vectors.inc"
PALETTE = [Party(30, 30, 31, True), Party(9, 9, 9, True), Party(25, 25, 16, True), Party(25, 15, 25, True),
           Party(25, None, 25, True), Party(25, 25, 25, False), Party(45, 44, 46, True)]
WRITE_VARS = ["r_affection", "r_attraction", "r_fear", "assurance", "fear", "m_valence", "need_intimacy",
              "b_certainty", "pain", "self_regard", "grief", "g_priority", "b_weight", "g_desired", "attracted_to"]


def cpp_age(a):
    return -1 if a is None else int(round(a * 10))


def main():
    cat = Catalogue.load()
    g = Governor(cat)
    rng = random.Random(20261010)
    L = ["// GENERATED by catalogue/tools/governor_vectors.py from the Python governor (oracle). Do not edit.",
         "// Party palette: {real, believed, apparent (tenths of years, -1 unknown), resolved}"]
    L.append("static const em::social::Party kPalette[] = {")
    for p in PALETTE:
        L.append(f"  {{{cpp_age(p.real_age)}, {cpp_age(p.believed_age)}, {cpp_age(p.apparent_age)}, {str(p.resolved).lower()}}},")
    L.append("};")
    # --- writes: sequences on one ledger per (variable, run)
    L.append("struct WriteCase { int seq; em::social::gen::Var var; short old_v; short proposed; bool creating; int target;"
             " int intimate_target; int actor; bool allowed; short value; };")
    L.append("static const WriteCase kWrites[] = {")
    seq = 0
    for vid in WRITE_VARS:
        for run in range(6):
            led = WriteLedger()
            seq += 1
            x = 0
            for _ in range(25):
                proposed = x + rng.randint(-40, 40)
                creating = rng.random() < 0.15
                ti, ai = rng.randint(-1, len(PALETTE) - 1), rng.randint(-1, len(PALETTE) - 1)
                v = g.check_write(vid, x / 10, proposed / 10, led, target="7",
                                  intimate_target=None if ti < 0 else PALETTE[ti], actor=None if ai < 0 else PALETTE[ai],
                                  creating=creating)
                val = 0 if v.value is None else tenths(v.value)
                L.append(f"  {{{seq}, em::social::gen::Var::{ident(vid)}, {x}, {proposed}, {str(creating).lower()}, 7, {ti}, {ai}, "
                         f"{str(v.allowed).lower()}, {val}}},")
                if v.allowed and v.value is not None:
                    x = val
    L.append("};")
    # --- gestures
    L.append("struct GestureCase { em::social::gen::Gesture gesture; signed char value[6]; signed char party[6]; int actor; bool allowed; };")
    L.append("static const GestureCase kGestureCases[] = {")
    for a in cat["action"].values():
        for _ in range(60):
            params, parties, vals, pidx = {}, {}, [-1] * 6, [-1] * 6
            for i, p in enumerate(a.params):
                if rng.random() < 0.25:
                    continue
                if p.type == "enum":
                    k = rng.randrange(len(p.values)); vals[i] = k; params[p.name] = p.values[k]
                elif p.type == "ref":
                    vals[i] = 0; params[p.name] = "@E1"
                else:
                    vals[i] = 0; params[p.name] = "x"
                if p.name in a.party_params and rng.random() < 0.85:
                    pi = rng.randrange(len(PALETTE)); pidx[i] = pi; parties[p.name] = PALETTE[pi]
            ai = rng.randint(-1, len(PALETTE) - 1)
            v = g.check_gesture(a.id, params, None if ai < 0 else PALETTE[ai], parties)
            L.append(f"  {{em::social::gen::Gesture::{ident(a.id)}, {{{', '.join(map(str, vals))}}}, {{{', '.join(map(str, pidx))}}}, "
                     f"{ai}, {str(v.allowed).lower()}}},")
    L.append("};")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"écrit {OUT}")


if __name__ == "__main__":
    main()
